### ISSUE TITLE
Possible confusion with the Disks view, in 'Chronology of Systematic Testing' figure

### ISSUE THREAD

**Issue by datajms** [Linc-tw/COVID_breakdown#14]
The first time I have seen the pyramid disk view, it took me some time to figure out that the disk pyramid was not a [risk pyramid](https://www.jjwhiteinc.com/2018/02/06/the-injury-pyramid/) but that the height is the time!

Changing the value per default to "Linear" could help figuring out the dimensions more quickly!

**Comment by Linc-tw** [comment]
Done. The size of the disk is actually the covering range, which became bigger & bigger. If this is not trivial then yeah, should be better to swap them.
