### ISSUE TITLE
Dataset in CoronaWhy Dataverse 

### ISSUE THREAD

**Issue by geek80** [Linc-tw/COVID_breakdown#16]
Hello,Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/CPP6SY

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by Linc-tw** [comment]
Not really interested in maintaining them outside this repo. 
I believe that people who find snapshots on CoronaWhy will be smart enough to land here for up-to-date data.
