### ISSUE TITLE
Cluster network

### ISSUE THREAD

**Issue by Linc-tw** [Linc-tw/COVID_breakdown#6]
Not sure whether it's interesting to show this: a network graph showing the links between confirmed cases if there are any. 

The reason is that most cases in Taiwan are weakly linked. The biggest cluster is the military fleet.

Also, is there any interesting (not superficial) information from the network? For example, gender or age histogram is a boring plot. It shows nothing different from a heuristic process. 

From a cluster network, one can probably calculate some indicators similar to the R-value. This will be interesting, but it's not necessary to draw a network "graph" to do so. There might be a better way to visualize the information. 

Pending & to rethink.

**Comment by anthonyhtyao** [comment]
We can try, but most of the cases  are imported. We might get lots of isolated points

**Comment by Linc-tw** [comment]
Not priority. I am more interested in timeline.

**Comment by Linc-tw** [comment]
Not going to do this.
