### ISSUE TITLE
Some remarks / suggestions 

### ISSUE THREAD

**Issue by PNarchi** [Linc-tw/COVID_breakdown#9]
## Graphs
- It could be nice to have an explanation on what is count and what is coefficient (a hoover could be an option) 
- Enable to download data as a csv

## Readme
- It is important to make the readme appealing. To this purpose, I would : 
. Project title
. Motivation
. Include a **Gif showing the interface** while navigating on it 
. Mention how to install the necessary libraries, if somebody wants to make the project
. Give some ideas on where does the project come from
. Credits
. Contribute + Contributing guidelines
. License 
==> Some good tips on readme can be found here: 
https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3

## Possible upgrades
- Access data by API in order to make automatic updates 
- Compare to other countries / Make graphs to compare two countries results
- Simple text mining analysis on local Taiwanese news on Covid to compare what is said with the figures. What are the main keywords that are discussed in local news, ...

**Comment by Linc-tw** [comment]
Thanks @PNarchi.

#### Graphs
Explanations on coefficients & counts would go to #3 
Download data as csv: I will turn "Data source" into a page where people a link to Google sheet & a link to `processed_data` where we have `.csv`. I will make a new issue.

#### Readme
Very nice suggestion & I will work on it.

#### Possible upgrades
Very interesting ideas, but I don't think I have time :(

**Comment by Linc-tw** [comment]
I have updated README & made references to other issues for other points. 

I will close this issue now but might come back for great ideas that I don't have time doing now.
